name: Frontend Linting

on:
  push:
    paths:
      - "front/**"
  pull_request:
    paths:
      - "front/**"

jobs:
  lint:
    name: Run Prettier and ESLint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check formatting with Prettier
        run: npm run lint
